### ISSUE TITLE
Discussion on a regression problem, please give more advice

### ISSUE THREAD

**Issue by Njzjhd** [JingweiToo/Advanced-Feature-Selection-Toolbox#1]
At the moment, I notice that many papers have been studied mostly on classification issues. I would like to ask what should the formula of the loss function look like if for the regression problem? Can you give me some suggestions? Thank you very much.

**Comment by JingweiToo** [comment]
Hi,

For regression, you may change the KNN in fitness function to other regression algorithm such as logistic regression. Also, the error rate can be changed to mean square error.

**Comment by Njzjhd** [comment]
ExtraTreeRegressor


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JingweiToo/Advanced-Feature-Selection-Toolbox"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 上午10:50
收件人:&nbsp;"JingweiToo/Advanced-Feature-Selection-Toolbox"<Advanced-Feature-Selection-Toolbox@noreply.github.com&gt;;
抄送:&nbsp;"至爱❤️"<2318109878@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JingweiToo/Advanced-Feature-Selection-Toolbox] Discussion on a regression problem, please give more advice (#1)





 
Hi,
 
For regression, you may change the KNN in fitness function to other regression algorithm such as logistic regression. Also, the error rate can be changed to mean square error.

**Comment by Njzjhd** [comment]
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JingweiToo/Advanced-Feature-Selection-Toolbox"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 上午10:50
收件人:&nbsp;"JingweiToo/Advanced-Feature-Selection-Toolbox"<Advanced-Feature-Selection-Toolbox@noreply.github.com&gt;;
抄送:&nbsp;"至爱❤️"<2318109878@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JingweiToo/Advanced-Feature-Selection-Toolbox] Discussion on a regression problem, please give more advice (#1)





 
Hi,
 
For regression, you may change the KNN in fitness function to other regression algorithm such as logistic regression. Also, the error rate can be changed to mean square error.
